version: 2.1

parameters:
  condition-workflow:
    type: boolean
    default: true

jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - when:
          condition:
            - equal: [main, << pipeline.git.branch >>]
          steps:
            - run: echo "I am on main"

  conditional-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This ran on a pipeline parameter"

workflows:
  version: 2
  my-workflow:
    jobs:
      - my-job

  conditional-workflow:
    when:
      and:
        - << pipeline.parameters.condition-workflow >>
    jobs:
      - conditional-job